---
title: "Analisis_Descriptivo"
author: "Valentina García - Jaime Molina"
date: "11/2/2020"
output:
  html_document:
    df_print: paged
---
```{r, message = FALSE, warning= FALSE}
# Cargar paquetes
library(tidyverse)
library(lubridate)
library(plotly)
```

```{r}
# lectura base de datos
datos <- read.csv("https://raw.githubusercontent.com/vagarciave/Project_x/master/modelo/Base_Completa_NAimp.csv", encoding = 'UTF-8', stringsAsFactors=FALSE)
```


```{r}
# Crear orden para los días
datos$DIA_NOMBRE <- factor(datos$DIA_NOMBRE,levels = c('LUNES','MARTES','MIERCOLES',
                                   'JUEVES','VIERNES','SABADO','DOMINGO'))
# Solo la fecha, sin hora
datos$FECHA <- sapply(datos$FECHA, function(x) substr(x,1,10))
```


```{r}
#  Vector con fechas de dias festivos
  # Definir dias festivos
  festivos <- ymd(c(
    #2014
    '2014-01-01','2014-01-06','2014-03-24','2014-04-17','2014-04-18', '2014-05-01',
    '2014-06-02','2014-06-23','2014-06-30','2014-07-20','2014-08-07', '2014-08-18',
    '2014-10-13','2014-11-03','2014-11-17','2014-12-08','2014-12-25',
    #2015
    '2015-01-01','2015-01-12','2015-03-23','2015-03-29','2015-04-02','2015-04-03',
    '2015-04-05','2015-05-01','2015-05-18','2015-06-08','2015-06-15','2015-06-29',
    '2015-07-20','2015-08-07', '2015-08-17','2015-10-12','2015-11-02','2015-11-16',
    '2015-12-08','2015-12-25',
    #2016
    '2016-01-01','2016-01-11','2016-03-20','2016-03-21','2016-03-24','2016-03-25',
    '2016-03-27','2016-05-01','2016-05-09','2016-05-30','2016-06-06','2016-07-04',
    '2016-07-20','2016-08-07', '2016-08-15','2016-10-17','2016-11-07','2016-11-14',
    '2016-12-08','2016-12-25',
    #2017
    '2017-01-01','2017-01-09','2017-03-20','2017-04-09','2017-04-13','2017-04-14',
    '2017-04-16','2017-05-01','2017-05-29','2017-06-19','2017-06-26','2017-07-03',
    '2017-07-20','2017-08-07', '2017-08-21','2017-10-16','2017-11-06','2017-11-13',
    '2017-12-08','2017-12-25',
    #2018
    '2018-01-01','2018-01-08','2018-03-19','2018-03-25','2018-03-29','2018-03-30',
    '2018-04-01','2018-05-01','2018-05-14','2018-06-04','2018-06-11','2018-07-02',
    '2018-07-20','2018-08-07', '2018-08-20','2018-10-15','2018-11-05','2018-11-11',
    '2018-12-08','2018-12-25'
    ))
dia_festivo <- ifelse(ymd(datos$FECHA) %in% festivos,1,0)

# Crear variable de dia festivo
datos$DIA_FESTIVO <- dia_festivo
```

## Análisis descriptivo

### Total de accidentes

```{r}
ds <- datos %>% mutate(Date = as.Date(FECHA)) %>% 
  group_by(FECHA) %>% 
  summarise(Total = n())
ds <- data.frame(Date = as.Date(ds$FECHA),Total = ds$Total)

fig <- plot_ly(ds, x = ~Date)
fig <- fig %>% add_lines(y = ~Total, name = "Total")
fig <- fig %>% layout(
    title = "Total de accidentes",
    xaxis = list(
      rangeselector = list(
        buttons = list(
          list(
            count = 3,
            label = "3 meses",
            step = "month",
            stepmode = "backward"),
          list(
            count = 6,
            label = "6 meses",
            step = "month",
            stepmode = "backward"),
          list(
            count = 1,
            label = "1 año",
            step = "year",
            stepmode = "backward"),
          list(step = "all"))),

      rangeslider = list(type = "date"))
    )

fig
```

### CLASE

```{r}
datos %>% group_by(CLASE) %>% 
  summarise(TOTAL = n())  %>% arrange(desc(TOTAL)) %>%
  plot_ly(x = ~ CLASE, y = ~ TOTAL,color = ~CLASE, type = 'bar')   %>%
  layout(
     title = "Total de accidentes por Clase",
     xaxis = list(title = "",
     categoryorder = "array",
     categoryarray = ~CLASE),
     yaxis = list(title = "Total")
    )

```

Boxplot para total de accidentes diarios por CLASE
```{r}
# Crear conteos por variable CLASE, agrupados por dia
datos_clase <- datos %>% group_by(FECHA,CLASE) %>% 
  summarise(TOTAL = n()) %>% 
  arrange(desc(TOTAL))
fig_clase <- datos_clase %>% plot_ly(y = ~ TOTAL, color = ~CLASE, type = "box")   %>%
  layout(
     title = "Total de accidentes por gravedad",
     xaxis = list(title = "",
     categoryorder = "array",
     categoryarray = ~CLASE),
     yaxis = list(title = "Total")
    )
#fig_clase <- fig_clase %>% layout(boxmode = "group")
fig_clase
```


### GRAVEDAD

```{r}
datos %>% group_by(GRAVEDAD) %>% 
  summarise(TOTAL = n())  %>% arrange(desc(TOTAL)) %>%
  plot_ly(x = ~ GRAVEDAD, y = ~ TOTAL,color = ~GRAVEDAD, type = 'bar')  %>%
  layout(
     title = "Total de accidentes por gravedad",
     xaxis = list(title = "",
     categoryorder = "array",
     categoryarray = ~GRAVEDAD),
     yaxis = list(title = "Total")
    )

```

### COMUNA 
```{r}
datos %>% group_by(COMUNA) %>% 
  summarise(TOTAL = n())  %>% arrange(desc(TOTAL)) %>%
  plot_ly(x = ~ COMUNA, y = ~ TOTAL,color = ~COMUNA, type = 'bar')  %>%
  layout(
     title = "Total de accidentes por Comuna",
     xaxis = list(title = "",
     categoryorder = "array",
     categoryarray = ~COMUNA),
     yaxis = list(title = "Total")
    )

```
### BARRIO
### DISENO
### DIA_NOMBRE
#### DIA_FESTIVO
## PERIODO

