---
title: "Modelos"
author: "Jaime Andres Molina Correa"
date: "8/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Se carga la base de datos

```{r}
datos <- read.csv("Base_definitiva.csv", header = T, stringsAsFactors = T,
                  encoding = "UTF-8")
```

Librerías

```{r, message=F, warning=F}
library(tidyverse)
library(dplyr)
library(magrittr)
library(lubridate)
library("zoo")

library(lme4)
library(gamlss)
library(randomForest)
```

Se agrega la variable TIEMPO y MES_NOMBRE
```{r}
datos$FECHA <- as.Date(datos$FECHA)

datos$MES_NOMBRE <- paste(datos$PERIODO, datos$MES, sep="-") %>% as.yearmon("%Y-%m")

# Para obtener la inversa se usaría: zoo::as.Date(datos$FECHA, origin="2014-01-01")
datos$TIEMPO <- as.numeric(as.Date(datos$FECHA)) - as.numeric(as.Date("2014-01-01")) + 1
```


```{r}
# datos$N_ACCIDENTES <- 1
# datos <- datos %>% spread(CLASE, N_ACCIDENTES, fill = 0)

# bd1 <- datos %>% count(COMUNA, PERIODO, FECHA, DIA_FESTIVO, TIEMPO,
#                        GRAVEDAD, Atropello, `Caida Ocupante`,
#                        Choque, Incendio, Otro, Volcamiento)
# str(bd1)
# bd1
```
La base tiene 85,981 observaciones 


```{r}
bd1 <- datos %>% count(COMUNA, CLASE, PERIODO, FECHA, TIEMPO, DIA_FESTIVO) %>% rename(CANTIDAD_T = n)
```


# Base de entrenamiento y de prueba:

```{r}
test <- bd1[bd1$PERIODO == 2018, ]
train <- bd1[bd1$PERIODO %in% c(2014, 2015, 2016, 2017), ]
```

# Funcion MSE
```{r}
MSE <- function(y, y_est) mean((y-y_est)**2)
```

# Modelos Mixtos

Modelo solo con efectos aleatorios en COMUNA

```{r, message=FALSE, warning=FALSE}
mod30 <- glmer(CANTIDAD_T ~ TIEMPO + DIA_FESTIVO +
                 (1 + TIEMPO | COMUNA),
               data = train, family= poisson())
```


```{r, message=FALSE, warning=FALSE}
summary(mod30)
```

```{r}
y_est30_train <- predict(mod30, newdata = train, type = "response")
y_est30_test <- predict(mod30, newdata = test, type = "response")
MSE(train$CANTIDAD_T, y_est30_train)
MSE(test$CANTIDAD_T, y_est30_test)
```

Modelo con efectos aleatorios en COMUNA y CLASE, CLASE dentro de COMUNA.

```{r, message=FALSE, warning=FALSE}
mod31 <- glmer(CANTIDAD_T ~ TIEMPO + DIA_FESTIVO +
                 (1 + TIEMPO | COMUNA/CLASE),
               data = train, family= poisson())
```

```{r, message=FALSE, warning=FALSE}
summary(mod31)
```

```{r}
y_est31_train <- predict(mod31, newdata = train, type = "response")
y_est31_test <- predict(mod31, newdata = test, type = "response")
MSE(train$CANTIDAD_T, y_est31_train)
MSE(test$CANTIDAD_T, y_est31_test)
```

```{r}
data.frame(observado = train$CANTIDAD_T, predicho = y_est31_train)[sample(1:length(y_est31_train), 500),]
```


Modelo con efectos aleatorios en COMUNA y CLASE, CLASE y COMUNA no anidadas.

```{r, message=FALSE, warning=FALSE}
mod32 <- glmer(CANTIDAD_T ~ TIEMPO + DIA_FESTIVO +
                 (1 + TIEMPO | COMUNA) + (1 + TIEMPO | CLASE),
               data = train, family= poisson())
```

```{r, message=FALSE, warning=FALSE}
summary(mod32)
```

```{r}
y_est32_train <- predict(mod32, newdata = train, type = "response")
y_est32_test <- predict(mod32, newdata = test, type = "response")
MSE(train$CANTIDAD_T, y_est32_train)
MSE(test$CANTIDAD_T, y_est32_test)
```



